name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
        cache: maven
        
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: java
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
